### ISSUE TITLE
Handling of writable items might fail starting with HA 2024.2.0

### ISSUE THREAD

**Issue by JongsmaSimon** [john30/ebusd-configuration#353] opened 2023-08-19 19:54 UTC
I have 3 writable items in my ebusd configuration.
Today (after HA upgrade) there appeared the following warning:

“This stops working in version 2024.2.0. Please address before upgrading.
 Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped off the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.”
List of affected entities:

number.ebusd_hmu_doeltempboiler
number.ebusd_hmu_doeltempwoning
number.ebusd_hmu_stooklijn

**Comment by edudele** [comment] 2023-08-21 07:39
here -> https://github.com/john30/ebusd/issues/975

**Comment by john30** [comment] 2023-09-03 16:45
duplicate of https://github.com/john30/ebusd/issues/975

**Closed by john30** 2023-09-03 16:45 UTC
