### ISSUE TITLE
Missing D.14 PumpPowerDesired

### ISSUE THREAD

**Issue by ikavior** [john30/ebusd-configuration#208] opened 2021-01-17 09:00 UTC
Hello.

I have Vaillant ecoTec Plus 206 with Multimatic 700 and in the ebusd I cant find position for D.014 PumpPowerDesired.

ebusd "vaillant/bai.308523.inc", "vaillant/08.bai.csv"

I found that this position is in the bai.0010015600.inc. How to make it working? :)

Thanks.

**Comment by john30** [comment] 2021-02-20 08:56
start with finding the product ID of the bai by issuing `ebusctl -f -d -c scan`. that has to be added to the bai.csv

**Comment by ikavior** [comment] 2021-02-20 08:59
scan.08  = Vaillant;BAI00;0104;7803
scan.08 id = 21;19;44;0010021887;0001;012451;N0
scan.15  = Vaillant;70000;0613;6903
scan.15 id = 21;19;43;0020171316;0082;026204;N4

**Comment by john30** [comment] 2021-02-20 10:07
duplicate of #210

**Closed by john30** 2021-02-20 10:07 UTC
Labels: duplicate, help wanted
