### ISSUE TITLE
Exacontrol E7C - no configuration file

### ISSUE THREAD

**Issue by szeryf85** [john30/ebusd-configuration#187] opened 2020-08-17 06:39 UTC
Hello,
I need help :)
I have an Exacontrol E7C controller, but there is no configuration file for it. I have tried 15.e7f.csv and 15.f47.csv with no success. Of course, in each file I changed "circuit" to E7C00. Asking for a parameter returns an error.

Below are some results after scanning (with 15.e7f.csv configuration file with circuit change to E7C00). Can you help me somehow?

root@064364137f43:/# ebusctl find
bai AccessoriesOne = no data stored
bai AccessoriesTwo = no data stored
(........)
bai WPPostrunTime = no data stored
bai WPSecondStage = no data stored
broadcast datetime = no data stored
broadcast error = no data stored
broadcast hwcStatus = no data stored
broadcast id = no data stored
broadcast id = no data stored
broadcast load = no data stored
broadcast outsidetemp = 21.625
broadcast signoflife = no data stored
broadcast vdatetime = 00:18:43;12.08.2020
e7c ActualWeekday = no data stored
e7c BatteryError = no data stored
e7c BMUErrorStatus = no data stored
e7c CMResetCnt = no data stored
e7c COMErrorCnt = no data stored
e7c ComfTempDesired = no data stored
e7c currenterror = no data stored
e7c Date = no data stored
e7c DisplayedRoomTemp = no data stored
e7c eBUSCommErrorPending = no data stored
e7c eBUSFifoDiffCntMax = no data stored
e7c EEpromMaxInkonsCnt = no data stored
e7c errorhistory = no data stored
e7c hcTimer.Friday = no data stored
e7c hcTimer.Monday = no data stored
e7c hcTimer.Saturday = no data stored
e7c hcTimer.Sunday = no data stored
e7c hcTimer.Thursday = no data stored
e7c hcTimer.Tuesday = no data stored
e7c hcTimer.Wednesday = no data stored
e7c HeatingCurve = no data stored
e7c HwcTempDesired = no data stored
e7c IsInHoliday = no data stored
e7c IsInQuickVeto = no data stored
e7c LVResetCnt = no data stored
e7c OperatingMode = no data stored
e7c OutsideTemp = (ERR: invalid position for 3115b509030d0300 / 0100)
e7c OutsideTempOffset = no data stored
e7c POCResetCnt = no data stored
e7c QuickVetoTemp = no data stored
e7c ReducedNightTemp = no data stored
e7c RfCommErrorPending = no data stored
e7c RoomTempOffset = no data stored
e7c RTCAdjustment = no data stored
e7c StackeBUSTaskMax = no data stored
e7c StackLifeCheckTaskMax = no data stored
e7c StackMainTaskMax = no data stored
e7c Time = (ERR: argument value out of valid range for 3115b509030d0700 / 0727848484848484)
e7c VariantDKRefreshCnt = no data stored
e7c WDResetCnt = no data stored
e7c WeekDayProgSwitch = no data stored
e7c YearCalendarActive = no data stored
e7c ZweipunktAnalogSlct = no data stored
general valuerange = no data stored
memory eeprom = no data stored
memory ram = no data stored
scan id = no data stored
scan.05 = no data stored
scan.08 = Vaillant;BAI00;0704;1303
scan.08 id = 21;18;39;0010016098;1610;005972;N0
scan.15 = Vaillant;E7C00;0212;7402
scan.15 id = 21;19;49;0020118071;0082;085050;N9

**Comment by john30** [comment] 2020-09-20 10:32
duplicate of #73

**Closed by john30** 2020-09-20 10:32 UTC
Labels: duplicate
